apiVersion: batch/v1
kind: Job
metadata:
  name: c4-noclean-80
spec:
  parallelism: 80 # 5x(4-5)C=20C-25C 5x(10-12)G=50-60G per node, (20C-25C)x89 = 1780C-2225C max: 445pod
  completions: 80
  backoffLimit: 5  # 如果任务失败后不希望重试，则设置为 0；否则设置为需要的重试次数
  template:
    metadata:
      labels:
        app: dclm-sci
    spec:
      imagePullSecrets:
        - name: cr-docker-registry
      containers:
      - name: dclm-sci
        image: cr.registry.res.cloud.zhejianglab.com/dataprocess/datarig:v4.9
        resources:
          requests:
            cpu: "26"
            memory: "52Gi"
          limits:
            cpu: "30"
            memory: "56Gi"
        command: ["/app/dclm-sci/start.sh"]
        env:
          - name: RAY_DEDUP_LOGS
            value: "0"
          - name: RAY_BACKEND_LOG_LEVEL
            value: "error"		
          - name: REDIS_HOST
            value: "10.200.48.152"
          - name: REDIS_PORT
            value: "6380"			
        args:
          - "--readable_name"
          - "c4_noclean_v2_short_line_1_sampled"
          - "--output_dir"
          - "oss://si002558te8h/dclm/output/"
          - "--config_path"
          - "baselines/baselines_configs/v2_test.yaml"
          - "--oss_temp_dir"
          - "oss://si002558te8h/dclm/pool/temp_dir_500/"
          - "--source_name"
          - "cc"
          - "--max_file_size_mb"
          - "500"
          - "--queue_id"
          - "url"
          - "--ray_num_cpus"
          - "1"
          - "--workers"
          - "1"
          - "--split_workers"
          - "8"		  
          - "--chunk_size"
          - "16"
          - "--output_has_dataset_name"
          - "--overwrite"
          - "--use_task"
          - "--use_redis_task"
          - "--ignore_failures"
        volumeMounts:
          - name: dclm-config-volume
            mountPath: "/app/dclm-sci/baselines/baselines_configs/v2_test.yaml"
            subPath: "v2_test.yaml"
        imagePullPolicy: IfNotPresent
      volumes:
        - name: dclm-config-volume
          configMap:
            name: dclm-config
      restartPolicy: OnFailure