apiVersion: batch/v1
kind: Job
metadata:
  name: datarig-job-2
spec:
  parallelism: 2 # 1246x2C 1246x4G
  completions: 2
  backoffLimit: 0  # 如果任务失败后不希望重试，则设置为 0；否则设置为需要的重试次数
  template:
    metadata:
      labels:
        app: dclm-sci
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - dclm-sci
              topologyKey: "kubernetes.io/hostname"
      imagePullSecrets:
        - name: cr-docker-registry
      containers:
      - name: dclm-sci
        image: cr.registry.res.cloud.zhejianglab.com/dataprocess/datarig:v1.4
        resources:
          requests:
            cpu: "4"
            memory: "8Gi"
          limits:
            cpu: "4"
            memory: "8Gi"
        command: ["/app/dclm-sci/start.sh"]
        env:
          - name: RAY_DISABLE_DUPLICATE_LOGS
            value: "1"		
        args:
          - "--readable_name"
          - "first_round_test3"
          - "--output_dir"
          - "oss://si002558te8h/dclm/output"
          - "--config_path"
          - "baselines/baselines_configs/sci.yaml"
          - "--oss_temp_dir"
          - "oss://si002558te8h/dclm/temp_dir_400/"
          - "--source_name"
          - "cc"
          - "--max_file_size_mb"
          - "400"
          - "--chunk_size"
          - "4"
          - "--output_has_dataset_name"
          - "--overwrite"
          - "--use_task"
          - "--ignore_failures"
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: dshm
            mountPath: /dev/shm
      restartPolicy: Never
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 5Gi