apiVersion: batch/v1
kind: Job
metadata:
  name: dedup-bff-fineweb-new
spec:
  parallelism: 5 # 5x(4-5)C=20C-25C 5x(10-12)G=50-60G per node, (20C-25C)x89 = 1780C-2225C max: 445pod
  completions: 5
  backoffLimit: 0  # 如果任务失败后不希望重试，则设置为 0；否则设置为需要的重试次数
  template:
    metadata:
      labels:
        app: dedup-bff
    spec: 
      imagePullSecrets:
        - name: cr-docker-registry
      containers:
      - name: dedup-bff
        image: cr.registry.res.cloud.zhejianglab.com/dataprocess/dedup-bff:v1.2
        resources:
          requests:
            cpu: "28"
            memory: "30Gi"
          limits:
            cpu: "30"
            memory: "32Gi"
        command: ["cargo","run"]
        env:
          - name: OSS_ACCESS_KEY_ID
            value: "D3XdW8uT66mdJ3TO"
          - name: OSS_ACCESS_KEY_SECRET
            value: "LpBPv841EkOhqNV8tiaknQfWJJm1uP"
        args:
          - "--release"
          - "bff"
          - "--tasks-file"
          - "oss://si002558te8h/dclm/dedup_tasks2.jsonl"
          - "--output-directory"
          - "oss://train1/basemodel-subjet-data-processed/r2/fineweb"
          - "--expected-ngram-count"
          - "100000"
          - "--fp-rate"
          - "0.01"
          - "--min-ngram-size"
          - "13"
          - "--max-ngram-size"
          - "13"
          - "--filtering-threshold"
          - "0.8"
          - "--remove-type"
          - "old-both"
          - "--annotate"
        imagePullPolicy: IfNotPresent
      restartPolicy: Never