apiVersion: batch/v1
kind: Job
metadata:
  name: datarig1-v3-3
spec:
  parallelism: 3 # 5x(4-5)C=20C-25C 5x(10-12)G=50-60G per node, (20C-25C)x89 = 1780C-2225C max: 445pod
  completions: 3
  backoffLimit: 5  # 如果任务失败后不希望重试，则设置为 0；否则设置为需要的重试次数
  template:
    metadata:
      labels:
        app: dclm-sci
    spec:
      imagePullSecrets:
        - name: cr-docker-registry
      containers:
      - name: dclm-sci
        image: cr.registry.res.cloud.zhejianglab.com/dataprocess/datarig:v3.0
        resources:
          requests:
            cpu: "4"
            memory: "10Gi"
          limits:
            cpu: "5"
            memory: "12Gi"
        command: ["/app/dclm-sci/start.sh"]
        env:
          - name: RAY_DEDUP_LOGS
            value: "0"
          - name: REDIS_HOST
            value: "10.200.48.152"
          - name: REDIS_PORT
            value: "6380"			
        args:
          - "--readable_name"
          - "v3_test"
          - "--output_dir"
          - "oss://si002558te8h/dclm/output"
          - "--config_path"
          - "baselines/baselines_configs/sci.yaml"
          - "--oss_temp_dir"
          - "oss://si002558te8h/dclm/pool/temp_dir_300/"
          - "--source_name"
          - "cc"
          - "--max_file_size_mb"
          - "300"
          - "--queue_id"
          - "default"
          - "--ray_num_cpus"
          - "1"
          - "--workers"
          - "1"
          - "--split_workers"
          - "4"		  
          - "--chunk_size"
          - "3"
          - "--output_has_dataset_name"
          - "--overwrite"
          - "--use_task"
          - "--use_redis_task"
          - "--ignore_failures"
        imagePullPolicy: IfNotPresent
      restartPolicy: OnFailure