apiVersion: batch/v1
kind: Job
metadata:
  name: datarig2-40
spec:
  parallelism: 40 # 2x(3-4)C=6C-8C 2x(12-15)G=24-30G per node, (6C-8C)x40 = 240C-320C max: 80pod 
  completions: 40
  backoffLimit: 0  # 如果任务失败后不希望重试，则设置为 0；否则设置为需要的重试次数
  template:
    metadata:
      labels:
        app: dclm-sci
    spec:
      imagePullSecrets:
        - name: cr-docker-registry
      containers:
      - name: dclm-sci
        image: cr.registry.res.cloud.zhejianglab.com/dataprocess/datarig:v2.4
        resources:
          requests:
            cpu: "3"
            memory: "12Gi"
          limits:
            cpu: "4"
            memory: "15Gi"
        command: ["/app/dclm-sci/start.sh"]
        env:
          - name: RAY_DEDUP_LOGS
            value: "0"
        args:
          - "--readable_name"
          - "Aerospace"
          - "--output_dir"
          - "oss://si002558te8h/dclm/output"
          - "--config_path"
          - "baselines/baselines_configs/sci.yaml"
          - "--oss_temp_dir"
          - "oss://si002558te8h/dclm/temp_dir_100/"
          - "--source_name"
          - "cc"
          - "--max_file_size_mb"
          - "100"
          - "--chunk_size"
          - "3" # 4 有可能出现 oom，不过没有影响最终产出
          - "--output_has_dataset_name"
          - "--overwrite"
          - "--use_task"
          - "--ignore_failures"
        imagePullPolicy: IfNotPresent
      restartPolicy: Never