apiVersion: v1
kind: Pod
metadata:
  name: redis-tester
spec:
  imagePullSecrets:
    - name: cr-docker-registry
  containers:
    - name: redis-cli
      image: cr.registry.res.cloud.zhejianglab.com/dataprocess/redis-tester:v0.1
      command: ["/bin/bash"]
      args: ["-c", "sleep infinity"]
      stdin: true
      tty: true
  restartPolicy: Never